- name: Update & Install
  hosts: localhost
  become: true
  tasks:
    - name: Run Update
      ansible.builtin.dnf5:
        name: "*"
        state: latest
    - name: Install
      ansible.builtin.dnf5:
        name: "tuba"
        state: present
